Repository materialsproject/emmet, pull requests merged in 2023-07, with the labels that each got.

#770 Pin pydantic
  emmet-core/setup.py
Labels: release:patch

#774 Add sorting to messages api endpoint
  emmet-api/emmet/api/routes/_messages/resources.py
  emmet-builders/setup.py
Labels: release:patch

#779 Electronic structure bug fixes
  emmet-builders/emmet/builders/materials/electronic_structure.py
Labels: release:minor

#780 Fix thermo material_id treatment in alloys
  emmet-builders/emmet/builders/materials/alloys.py
Labels: release:patch

#783 Don't calculate band properties if LORBIT < 11
  emmet-core/emmet/core/vasp/calculation.py
Labels: release:patch

#785 Small fixes for `TaskDoc`
  emmet-core/emmet/core/tasks.py
Labels: release:patch

#789 Automated dependency upgrades
  emmet-api/requirements/macos-latest_py3.10.txt
  emmet-api/requirements/macos-latest_py3.10_extras.txt
  emmet-api/requirements/macos-latest_py3.11.txt
  emmet-api/requirements/macos-latest_py3.11_extras.txt
  emmet-api/requirements/macos-latest_py3.8.txt
  emmet-api/requirements/macos-latest_py3.8_extras.txt
  emmet-api/requirements/macos-latest_py3.9.txt
  emmet-api/requirements/macos-latest_py3.9_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.10.txt
  emmet-api/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.11.txt
  emmet-api/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.8.txt
  emmet-api/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.9.txt
  emmet-api/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/requirements/macos-latest_py3.10.txt
  emmet-builders/requirements/macos-latest_py3.10_extras.txt
  emmet-builders/requirements/macos-latest_py3.11.txt
  emmet-builders/requirements/macos-latest_py3.11_extras.txt
  emmet-builders/requirements/macos-latest_py3.8.txt
  emmet-builders/requirements/macos-latest_py3.8_extras.txt
  emmet-builders/requirements/macos-latest_py3.9.txt
  emmet-builders/requirements/macos-latest_py3.9_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.10.txt
  emmet-builders/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.11.txt
  emmet-builders/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.8.txt
  emmet-builders/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.9.txt
  emmet-builders/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-core/requirements/macos-latest_py3.10.txt
  emmet-core/requirements/macos-latest_py3.10_extras.txt
  emmet-core/requirements/macos-latest_py3.11.txt
  emmet-core/requirements/macos-latest_py3.11_extras.txt
  emmet-core/requirements/macos-latest_py3.8.txt
  emmet-core/requirements/macos-latest_py3.8_extras.txt
  emmet-core/requirements/macos-latest_py3.9.txt
  emmet-core/requirements/macos-latest_py3.9_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.10.txt
  emmet-core/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.11.txt
  emmet-core/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.8.txt
  emmet-core/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.9.txt
  emmet-core/requirements/ubuntu-latest_py3.9_extras.txt
Labels: release:minor

#791 CI run pytest even if `mypy` errors
  .github/workflows/testing.yml
Labels: ci

#775 Fix molecules hint scheme
  emmet-api/emmet/api/routes/molecules/summary/hint_scheme.py
  emmet-api/tests/molecules/summary/test_hint_scheme.py
Labels: release:patch
