Repository materialsproject/emmet, pull requests merged in 2023-09, with the labels that each got.

#824 Add `is_hubbard` and `hubbards` to entry.parameters
  emmet-core/emmet/core/tasks.py
  emmet-core/emmet/core/vasp/calculation.py
Labels: release:minor

#806 Add `MLBuilder` and `MLDoc` to record machine learning property predictions
  docs/CHANGELOG.md
  emmet-api/requirements/ubuntu-latest_py3.10.txt
  emmet-api/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.11.txt
  emmet-api/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.8.txt
  emmet-api/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.9.txt
  emmet-api/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/emmet/builders/materials/corrected_entries.py
  emmet-builders/emmet/builders/materials/ml.py
  emmet-builders/requirements/ubuntu-latest_py3.10.txt
  emmet-builders/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.11.txt
  emmet-builders/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.8.txt
  emmet-builders/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.9.txt
  emmet-builders/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/tests/test_ml.py
  emmet-core/emmet/core/elasticity.py
  emmet-core/emmet/core/feff/task.py
  emmet-core/emmet/core/ml.py
  emmet-core/emmet/core/phonon.py
  emmet-core/emmet/core/structure.py
  emmet-core/emmet/core/thermo.py
  emmet-core/emmet/core/utils.py
  emmet-core/requirements/ubuntu-latest_py3.10.txt
  emmet-core/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.11.txt
  emmet-core/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.8.txt
  emmet-core/requirements/ubuntu-latest_py3.8_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.9.txt
  emmet-core/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-core/setup.py
  emmet-core/tests/__init__.py
  emmet-core/tests/test_calculation.py
  emmet-core/tests/test_chemenv.py
  emmet-core/tests/test_magnetism.py
  emmet-core/tests/test_ml.py
  emmet-core/tests/test_molecule_metadata.py
  emmet-core/tests/test_optimade.py
  emmet-core/tests/test_oxidation_states.py
  emmet-core/tests/test_robocrys.py
  emmet-core/tests/test_structure_metadata.py
  setup.cfg
Labels: enhancement, Core, Builders

#836 Small pydantic related bug fixes and linting
  emmet-builders/emmet/builders/abinit/sound_velocity.py
  emmet-core/emmet/core/elasticity.py
  emmet-core/emmet/core/electronic_structure.py
  emmet-core/emmet/core/qchem/molecule.py
  emmet-core/emmet/core/structure_group.py
  emmet-core/emmet/core/substrates.py
  emmet-core/emmet/core/tasks.py
  emmet-core/emmet/core/vasp/validation.py
Labels: release:patch

#838 Remove PyObject pydantic type from model type hints
  emmet-core/emmet/core/settings.py
  emmet-core/emmet/core/vasp/validation.py
  emmet-core/tests/vasp/test_vasp.py
Labels: release:patch
