Repository materialsproject/emmet, pull requests merged in 2023-11, with the labels that each got.

#874 Add `summary_stats` attr to `emmet.core.vasp.calculation.PotcarSpec`
  emmet-core/emmet/core/vasp/calculation.py
Labels: enhancement, needs test, vasp

#880 Incorporate blessed tasks endpoint
  emmet-api/emmet/api/routes/materials/materials/query_operators.py
  emmet-api/emmet/api/routes/materials/materials/resources.py
  emmet-api/material_resources.py
  emmet-core/emmet/core/vasp/material.py
  emmet-core/tests/vasp/test_materials.py
Labels: release:minor

#869 Add `run_ddec6` option to `Calculation.from_vasp_files`
  emmet-core/emmet/core/vasp/calculation.py
  emmet-core/tests/test_calculation.py
Labels: enhancement, Core

#891 Cli backup expansion
  emmet-cli/emmet/cli/bash_scripts/launcher_finder
  emmet-cli/emmet/cli/tasks.py
  emmet-cli/setup.py
Labels: CLI

#893 Fix `MLDoc` broken schema
  emmet-core/emmet/core/elasticity.py
  emmet-core/emmet/core/fermi.py
  emmet-core/emmet/core/ml.py
Labels: fix

#894 Fix summary timeouts
  emmet-api/emmet/api/routes/materials/materials/hint_scheme.py
  emmet-api/emmet/api/routes/materials/materials/query_operators.py
  emmet-api/emmet/api/routes/materials/materials/resources.py
  emmet-api/emmet/api/routes/materials/summary/hint_scheme.py
  emmet-api/tests/materials/materials/test_hint_scheme.py
  emmet-api/tests/materials/materials/test_query_operators.py
  emmet-builders/tests/test_ml.py
  emmet-core/tests/test_ml.py
Labels: release:patch

#903 Handle data license
  emmet-builders/emmet/builders/materials/corrected_entries.py
  emmet-builders/emmet/builders/materials/oxidation_states.py
  emmet-builders/emmet/builders/settings.py
  emmet-builders/emmet/builders/vasp/materials.py
  emmet-builders/tests/test_chemenv.py
  emmet-builders/tests/test_oxidation.py
  emmet-core/emmet/core/summary.py
  emmet-core/emmet/core/thermo.py
  emmet-core/emmet/core/vasp/material.py
  emmet-core/emmet/core/vasp/task_valid.py
Labels: release:patch

#886 Improve trajectory handling for MD
  emmet-core/emmet/core/tasks.py
  emmet-core/emmet/core/vasp/calculation.py
Labels: release:patch

#905 Ensure RunType enum variants are case insensitive
  emmet-core/emmet/core/vasp/calc_types/enums.py
Labels: release:patch

#906 Fix summary hint scheme for excluding elements
  emmet-api/emmet/api/routes/materials/summary/hint_scheme.py
Labels: release:patch
