Repository materialsproject/emmet, pull requests merged in 2023-10, with the labels that each got.

#846 Automated dependency upgrades
  emmet-api/requirements/ubuntu-latest_py3.10.txt
  emmet-api/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.11.txt
  emmet-api/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.9.txt
  emmet-api/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.10.txt
  emmet-builders/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.11.txt
  emmet-builders/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.9.txt
  emmet-builders/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.10.txt
  emmet-core/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.11.txt
  emmet-core/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.9.txt
  emmet-core/requirements/ubuntu-latest_py3.9_extras.txt
Labels: release:patch

#848 Enable querying based on license data in builder meta
  emmet-api/emmet/api/routes/materials/materials/query_operators.py
  emmet-api/emmet/api/routes/materials/materials/resources.py
  emmet-api/emmet/api/routes/materials/oxidation_states/resources.py
  emmet-api/emmet/api/routes/materials/thermo/resources.py
  emmet-builders/emmet/builders/materials/thermo.py
Labels: release:patch

#854 Automated dependency upgrades
  emmet-api/requirements/ubuntu-latest_py3.10.txt
  emmet-api/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.11.txt
  emmet-api/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.9.txt
  emmet-api/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.10.txt
  emmet-builders/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.11.txt
  emmet-builders/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.9.txt
  emmet-builders/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.10.txt
  emmet-core/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.11.txt
  emmet-core/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.9.txt
  emmet-core/requirements/ubuntu-latest_py3.9_extras.txt
Labels: release:minor

#857 `MoleculeMetadata` set model config `allow='extra'`
  emmet-api/app.py
  emmet-core/emmet/core/base.py
  emmet-core/emmet/core/structure.py
  emmet-core/tests/test_molecule_metadata.py
Labels: Core, release:patch, fix, pydantic

#858 Fix search stats query op
  emmet-api/emmet/api/routes/materials/summary/query_operators.py
Labels: release:patch

#859 Fix density validator
  emmet-core/emmet/core/tasks.py
Labels: release:patch

#864 `_parse_additional_json` ignore `FW.json(.gz)`
  emmet-core/emmet/core/tasks.py
Labels: Core, fix, ecosystem

#863 Add 3 missing `Optional`s for `EmmetMeta` fields
  emmet-core/emmet/core/base.py
Labels: Core, release:patch, fix, pydantic

#865 Fix NSCF line mode task type iden
  emmet-core/emmet/core/vasp/calc_types/utils.py
Labels: release:patch

#866 Fix PyPI missing project description
  README.md
  emmet-api/setup.py
  emmet-builders/setup.py
  emmet-cli/setup.py
  emmet-core/setup.py
Labels: qa, pkg

#868 Fix incar handling in elasticity
  emmet-builders/emmet/builders/materials/elasticity.py
Labels: release:patch

#877 Fix new elasticity sub field in summary
  emmet-api/emmet/api/routes/materials/elasticity/query_operators.py
  emmet-api/emmet/api/routes/materials/elasticity/resources.py
  emmet-api/tests/materials/elasticity/test_query_operators.py
  emmet-builders/emmet/builders/materials/summary.py
Labels: release:minor
