Repository materialsproject/emmet, pull requests merged in 2024-05, with the labels that each got.

#998 Automated dependency upgrades
  emmet-api/requirements/ubuntu-latest_py3.10.txt
  emmet-api/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.11.txt
  emmet-api/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-api/requirements/ubuntu-latest_py3.9.txt
  emmet-api/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-builders/emmet/builders/utils.py
  emmet-builders/requirements/ubuntu-latest_py3.10.txt
  emmet-builders/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.11.txt
  emmet-builders/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-builders/requirements/ubuntu-latest_py3.9.txt
  emmet-builders/requirements/ubuntu-latest_py3.9_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.10.txt
  emmet-core/requirements/ubuntu-latest_py3.10_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.11.txt
  emmet-core/requirements/ubuntu-latest_py3.11_extras.txt
  emmet-core/requirements/ubuntu-latest_py3.9.txt
  emmet-core/requirements/ubuntu-latest_py3.9_extras.txt
Labels: release:patch

#999 move undeform_structure function to core utils
  emmet-builders/emmet/builders/vasp/materials.py
  emmet-core/emmet/core/utils.py
Labels: release:patch

#1011 Change default values in document model for TaskDocument.output.stress/forces
  emmet-core/emmet/core/vasp/task_valid.py
Labels: pydantic

#1019 setup.py fixes to include mp_potcar_stats in emmet-builders package
  emmet-builders/MANIFEST.in
  emmet-builders/setup.py
Labels: Builders, release:minor
