Repository materialsproject/emmet, pull requests merged in 2024-03, with the labels that each got.

#948 Fix docs wflow python version
  .github/workflows/release.yml
  emmet-api/tests/materials/materials/test_query_operators.py
  emmet-api/tests/materials/mpcomplete/test_query_operators.py
Labels: release:patch

#957 Fix hydrogen element injection in anonymous formula queries
  emmet-api/emmet/api/routes/materials/materials/utils.py
Labels: release:patch

#966 replace check for potcar hash with check for potcar summary stats
  emmet-builders/emmet/builders/utils.py
  emmet-builders/emmet/builders/vasp/task_validator.py
  emmet-builders/tests/test_materials.py
  emmet-builders/tests/test_utils.py
  emmet-builders/tests/test_vasp.py
  emmet-core/emmet/core/settings.py
  emmet-core/emmet/core/vasp/validation.py
  emmet-core/tests/vasp/test_vasp.py
  test_files/failed_elastic_task.json.gz
Labels: release:minor

#970 Changes for tackling the LevelOfTheory errors
  emmet-core/emmet/core/qc_tasks.py
  emmet-core/emmet/core/qchem/calculation.py
  emmet-core/tests/conftest_qchem.py
  emmet-core/tests/test_qc_task.py
Labels: release:minor

#972 Fix potcar checking
  emmet-builders/emmet/builders/utils.py
  emmet-builders/emmet/builders/vasp/mp_potcar_stats.json.gz
  emmet-builders/setup.py
  emmet-builders/tests/test_utils.py
  emmet-cli/emmet/cli/calc.py
  emmet-core/emmet/core/vasp/validation.py
Labels: release:minor

#973 bump matminer
  emmet-builders/setup.py
Labels: dependencies, release:patch
