Repository materialsproject/emmet, pull requests merged in 2024-01, with the labels that each got.

#916 Fix `matcalc.util->utils` module rename
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .github/workflows/upgrade-dependencies.yml
  emmet-builders/emmet/builders/materials/ml.py
  emmet-builders/tests/test_ml.py
  emmet-core/emmet/core/ml.py
  emmet-core/emmet/core/provenance.py
  emmet-core/setup.py
  emmet-core/tests/test_ml.py
Labels: dependencies

#922 Minor patch to electrode
  emmet-core/emmet/core/electrode.py
Labels: release:patch

#928 Allow ULID for MPIDS
  emmet-builders/emmet/builders/materials/electrodes.py
  emmet-core/emmet/core/mpid.py
  emmet-core/emmet/core/structure_group.py
  emmet-core/tests/test_mpid.py
  emmet-core/tests/test_structure_group.py
Labels: release:minor
